---

- name: install ntpdate
  register: install
  apt: { name: ntpdate }

- assert:
    that: servers_configurations[inventory_hostname] is defined
    fail_msg: "dans infra-data/vars/direct/ntp.yml, définir le serveur {{ inventory_hostname }} dans servers_configurations"

- name: configure ntpdate
  register: configure
  template:
    src: conf.j2
    dest: /etc/ntp.conf
    
- name: run after config
  when: install.changed or configure.changed
  failed_when: False
  command: ntpdate-debian

- name: setup crontab
  template:
    src: ntpdate.j2
    dest: /etc/cron.d/ntpdate
